### ISSUE TITLE
Remove explicit any

### ISSUE THREAD

**Issue by rodolphocastro** [rodolphocastro/dixture#18]
`deno lint --unstable` show us some errors on the module.

This issue covers fixing the `no-explicit-any` problems. More info on why this rule is triggered [can be found on ESLint]()

```
(no-explicit-any) `any` type is not allowed
  (subject[field] as any) = fieldValue;
                     ^^^
    at E:\Src\dixture\src\_simpleGenerator.ts:127:21

(no-explicit-any) `any` type is not allowed
  BigInt: (...params: any[]) => bigint;
                      ^^^
    at E:\Src\dixture\src\_factory.ts:16:22

(no-explicit-any) `any` type is not allowed
  Bool: (...params: any[]) => boolean;
                    ^^^
    at E:\Src\dixture\src\_factory.ts:21:20

(no-explicit-any) `any` type is not allowed
  Number: (...params: any[]) => number;
                      ^^^
    at E:\Src\dixture\src\_factory.ts:26:22

(no-explicit-any) `any` type is not allowed
  String: (...params: any[]) => string;
                      ^^^
    at E:\Src\dixture\src\_factory.ts:31:22

(no-explicit-any) `any` type is not allowed
  Int: (...params: any[]) => number;
                   ^^^
    at E:\Src\dixture\src\_factory.ts:41:19

(no-explicit-any) `any` type is not allowed
  FutureDate: (...params: any[]) => Date;
                          ^^^
    at E:\Src\dixture\src\_factory.ts:46:26

(no-explicit-any) `any` type is not allowed
  PastDate: (...params: any[]) => Date;
                        ^^^
    at E:\Src\dixture\src\_factory.ts:51:24

(no-explicit-any) `any` type is not allowed
  new (...args: any[]): T;
                ^^^
    at E:\Src\dixture\src\_factory.ts:73:16

(no-explicit-any) `any` type is not allowed
  resolve: (...args: any[]) => T[K];
                     ^^^
    at E:\Src\dixture\src\_factory.ts:81:21

(no-explicit-any) `any` type is not allowed
  protected readonly ruleSets: BaseRuleSet<any>[] = [];
                                           ^^^
    at E:\Src\dixture\src\_factory.ts:157:43

(no-explicit-any) `any` type is not allowed
  constructor(...args: BaseRuleSet<any>[]) {
                                   ^^^
    at E:\Src\dixture\src\_factory.ts:159:35
```

**Comment by rodolphocastro** [comment]
Some notes on this one:

> For now I'll be disabling this rule for `Factories` since they rely on being able to cast stuff from any into T and from T into any. Perhaps in the future we can better handle this.
